if(NOT DEFINED REFERENCE_DIR)
    message(FATAL_ERROR "REFERENCE_DIR is required")
endif()

set(manifest_path "${REFERENCE_DIR}/manifest.json")
if(NOT EXISTS "${manifest_path}")
    message(FATAL_ERROR "missing ReSTIR reference manifest: ${manifest_path}")
endif()

file(READ "${manifest_path}" manifest_json)
string(JSON schema GET "${manifest_json}" schema_version)
if(NOT schema STREQUAL "restir_di_reference_manifest_v0")
    message(FATAL_ERROR "unexpected ReSTIR reference schema: ${schema}")
endif()

string(JSON image_count LENGTH "${manifest_json}" images)
if(NOT image_count EQUAL 3)
    message(FATAL_ERROR "ReSTIR reference manifest must contain exactly three images")
endif()

math(EXPR last_image "${image_count} - 1")
foreach(index RANGE 0 ${last_image})
    string(JSON relative_path GET "${manifest_json}" images ${index} path)
    string(JSON expected_sha256 GET "${manifest_json}" images ${index} sha256)
    set(image_path "${REFERENCE_DIR}/${relative_path}")
    if(NOT EXISTS "${image_path}")
        message(FATAL_ERROR "missing ReSTIR reference image: ${image_path}")
    endif()
    file(SIZE "${image_path}" image_size)
    if(image_size LESS_EQUAL 0)
        message(FATAL_ERROR "empty ReSTIR reference image: ${image_path}")
    endif()
    file(SHA256 "${image_path}" actual_sha256)
    if(NOT actual_sha256 STREQUAL expected_sha256)
        message(FATAL_ERROR
            "ReSTIR reference hash mismatch for ${relative_path}: ${actual_sha256}")
    endif()
endforeach()

message(STATUS "Verified ${image_count} ReSTIR reference images")
