if(NOT DEFINED REFERENCE_DIR)
    message(FATAL_ERROR "REFERENCE_DIR is required")
endif()

set(manifest_path "${REFERENCE_DIR}/manifest.json")
if(NOT EXISTS "${manifest_path}")
    message(FATAL_ERROR "missing ReSTIR reference manifest: ${manifest_path}")
endif()

file(READ "${manifest_path}" manifest_json)
string(JSON schema GET "${manifest_json}" schema_version)
if(NOT schema STREQUAL "restir_di_reference_manifest_v2")
    message(FATAL_ERROR "unexpected ReSTIR reference schema: ${schema}")
endif()

string(JSON quality_limit GET "${manifest_json}" gates equal_or_better_quality_mse_ratio_limit)
if(NOT quality_limit EQUAL 1)
    message(FATAL_ERROR "ReSTIR quality ratio limit must require equal-or-better MSE")
endif()
string(JSON expected_quality_decision GET "${manifest_json}" gates expected_quality_decision)
if(NOT expected_quality_decision STREQUAL "selected")
    message(FATAL_ERROR "promoted spatial ReSTIR candidate must remain selected")
endif()
string(JSON spatial_neighbors GET "${manifest_json}" scene restir_spatial_neighbors)
if(NOT spatial_neighbors EQUAL 1)
    message(FATAL_ERROR "promoted ReSTIR contract requires exactly one spatial donor")
endif()
string(JSON bias_correction GET "${manifest_json}" scene restir_bias_correction)
if(NOT bias_correction STREQUAL "basic")
    message(FATAL_ERROR "promoted ReSTIR contract requires BASIC bias correction")
endif()
string(JSON performance_trial_count GET "${manifest_json}" gates performance_trial_count)
string(JSON minimum_performance_wins GET "${manifest_json}" gates minimum_performance_wins)
if(NOT performance_trial_count EQUAL 5 OR NOT minimum_performance_wins EQUAL 3)
    message(FATAL_ERROR "ReSTIR promotion requires a five-trial majority performance gate")
endif()
string(JSON first_spatial_reuse GET "${manifest_json}" gates first_spatial_reuse_pixels)
string(JSON reset_spatial_reuse GET "${manifest_json}" gates reset_spatial_reuse_pixels)
if(NOT first_spatial_reuse EQUAL 0 OR NOT reset_spatial_reuse EQUAL 0)
    message(FATAL_ERROR "spatial ReSTIR must reject first-frame and reset history")
endif()
string(JSON first_bias_corrected GET "${manifest_json}" gates first_bias_corrected_pixels)
string(JSON reset_bias_corrected GET "${manifest_json}" gates reset_bias_corrected_pixels)
if(NOT first_bias_corrected EQUAL 0 OR NOT reset_bias_corrected EQUAL 0)
    message(FATAL_ERROR "ReSTIR bias correction must reject first-frame and reset history")
endif()

string(JSON image_count LENGTH "${manifest_json}" images)
if(NOT image_count EQUAL 3)
    message(FATAL_ERROR "ReSTIR reference manifest must contain exactly three images")
endif()

math(EXPR last_image "${image_count} - 1")
foreach(index RANGE 0 ${last_image})
    string(JSON relative_path GET "${manifest_json}" images ${index} path)
    string(JSON expected_sha256 GET "${manifest_json}" images ${index} sha256)
    set(image_path "${REFERENCE_DIR}/${relative_path}")
    if(NOT EXISTS "${image_path}")
        message(FATAL_ERROR "missing ReSTIR reference image: ${image_path}")
    endif()
    file(SIZE "${image_path}" image_size)
    if(image_size LESS_EQUAL 0)
        message(FATAL_ERROR "empty ReSTIR reference image: ${image_path}")
    endif()
    file(SHA256 "${image_path}" actual_sha256)
    if(NOT actual_sha256 STREQUAL expected_sha256)
        message(FATAL_ERROR
            "ReSTIR reference hash mismatch for ${relative_path}: ${actual_sha256}")
    endif()
endforeach()

message(STATUS "Verified ${image_count} ReSTIR reference images")
